# Generated by Django 4.0.5 on 2022-06-09 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_ingredient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 6, 9, 14, 41, 30, 482025)),
        ),
    ]
