# Generated by Django 4.0.5 on 2022-06-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_menuitem_id_alter_purchase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
